### ISSUE TITLE
rake test is aborted

### ISSUE THREAD

**Issue by changeworld** [bm-sms/daimon_news-layout#26]
Hi owners!
I try `bin/setup` and `bundle exec rake test`.
Then, the following error occurred.
I try `gem install rails`.
However, it does not resolve the error.
I follow the procedure of README, but what procedure is missing?

```
$ bundle exec rake test
/Users/takashitakebayashi/Desktop/vcs/github/daimon_news-layout/lib/daimon_news/layout/engine.rb:2:in `<module:Layout>': uninitialized constant Rails (NameError)
	from /Users/xxx/Desktop/vcs/github/daimon_news-layout/lib/daimon_news/layout/engine.rb:1:in `<top (required)>'
	from /Users/xxx/Desktop/vcs/github/daimon_news-layout/lib/daimon_news/layout.rb:2:in `require'
	from /Users/xxx/Desktop/vcs/github/daimon_news-layout/lib/daimon_news/layout.rb:2:in `<top (required)>'
	from /Users/xxx/Desktop/vcs/github/daimon_news-layout/test/test_helper.rb:2:in `require'
	from /Users/xxx/Desktop/vcs/github/daimon_news-layout/test/test_helper.rb:2:in `<top (required)>'
	from /Users/xxx/Desktop/vcs/github/daimon_news-layout/test/daimon_news/layout_test.rb:1:in `require'
	from /Users/xxx/Desktop/vcs/github/daimon_news-layout/test/daimon_news/layout_test.rb:1:in `<top (required)>'
	from /Users/xxx/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:15:in `require'
	from /Users/xxx/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	from /Users/xxx/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `select'
	from /Users/xxx/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test:lib" -I"/Users/xxx/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib" "/Users/xxx/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/daimon_news/layout_test.rb" ]
/Users/xxx/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
/Users/xxx/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by cafedomancer** [comment]
Maybe, this gem is not supposed to be tested because it's just for a container of styles. I have no idea about how to solve this problem. @bm-sms/daimon-contributors have any thoughts?

**Comment by changeworld** [comment]
> Maybe, this gem is not supposed to be tested because it's just for a container of styles.

Ooooops!!

It is written in the README like this ...

> Development
> After checking out the repo, run bin/setup to install dependencies. Then, run rake test to run the tests. You can also run bin/console for an interactive prompt that will allow you to experiment.

I can not test it for the time being, but I will send a Pull Request for layout change.
